services:
  warehouse.api:
    image: warehouse.api
    build:
      context: .
      dockerfile: Src/Warehouse/Warehouse.Api/Dockerfile


  catalog.api:
    image: catalog.api
    build:
      context: .
      dockerfile: Src/Catalog/Catalog.Api/Dockerfile
