services:
            
  warehouseservice.api:
    image: warehouseservice.api
    build:
      context: .
      dockerfile: Src/Warehouse/WarehouseService.Api/Dockerfile



  postgres_WarehouseService:
    image: postgres:16.2
    container_name: postgres_WarehouseService_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB : RideMarketDb
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    networks:
      - WarehouseService-Network
    volumes:
      - postgres-WarehouseService:/data/postgres
    restart: unless-stopped

  pgadmin_WarehouseService:
    image: dpage/pgadmin4
    container_name: pgadmin_WarehouseService_container
    environment:
      PGADMIN_DEFAULT_EMAIL: pouya@gmail.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    volumes:
      - pgadmin-WarehouseService:/var/lib/pgadmin
    ports:
      - "8090:80"
    networks:
      - WarehouseService-Network
    restart: unless-stopped
    depends_on:
      - postgres_WarehouseService

  consul:
    image: hashicorp/consul:latest
    container_name: consul_service-coordinator
    restart: always
    ports:
      - "8500:8500"       # HTTP API + UI
      - "8600:8600/tcp"   # DNS
      - "8600:8600/udp"   # DNS
    command:
      - agent -dev  -client=0.0.0.0 -bind=0.0.0.0 -ui
    environment:
      - CONSUL_LOCAL_CONFIG={"ui_config": {"enabled": true}}
    volumes:
      - consul-data:/consul/data
      
volumes:
  postgres-WarehouseService:
  pgadmin-WarehouseService:
  consul-data:


networks:
  WarehouseService-Network:
    driver: bridge