# This is a generated file. Not intended for manual editing.
services:
  warehouseservice.api:
    build:
      context: "D:\\Projects\\EPart"
      dockerfile: "Src/Warehouse/WarehouseService.Api/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net10.0/WarehouseService.Api.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "warehouseservice.api:dev"
    ports: []
    volumes:
    - "D:\\Projects\\EPart\\Src\\Warehouse\\WarehouseService.Api:/app:rw"
    - "D:\\Projects\\EPart:/src:rw"
    - "C:\\Users\\Pouya\\.nuget\\packages:/home/app/.nuget/packages"
    working_dir: "/app"
